### ISSUE TITLE
Bug: Interfering with ChatGPT theme

### ISSUE THREAD

**Issue by nhan000** [travisvn/edge-tts-chrome-extension#2] opened 2024-12-04 14:52 UTC
Seems to affect dark mode very badly
![image](https://github.com/user-attachments/assets/18894419-3f58-4a0b-a1e6-d38a9037853e)

**Comment by travisvn** [comment] 2024-12-05 00:14
@nhan000 I'll investigate this — I anticipate I know what the issue is. Thank you for bringing it to my attention

**Comment by travisvn** [comment] 2024-12-05 06:32
@nhan000 The issue should be fixed..! 

https://github.com/travisvn/edge-tts-chrome-extension/commit/bfc1585c52cfee67d923f2f785703388fe14f82c

However, Google requires approval for any changes (even if they're relatively trivial like this), and it might take a day or two before the official plugin is updated to the new version. 

If you'd like, you can follow the readme on how to run the extension from the `dist` directory or the extracted `dist.zip` file.

**Closed by travisvn** 2024-12-05 06:32 UTC
